spring:
  application:
    name: main

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/sodamsodam_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kakao:
  api_key: ${API_KEY}
  redirect_uri: ${REDIRECT_URI}